### PR TITLE
fix wrong region key to bucketRegion

### PR DESCRIPTION
**Pull request by thelittlebug**

### CODE REVIEW

**Comment by coolaj86** [comment]
@cderche Can you confirm that this is the intended fix (i.e. we shouldn't rename the other variable that's listed here: https://github.com/cderche/greenlock-storage-s3/blob/master/lib/aws.js#L6 ?)

**Comment by coolaj86** [comment]
@thelittlebug Can you confirm that you can connect to non-default bucket regions with the change?

**Comment by coolaj86** [comment]
Since I haven't heard back, but this looks reasonable to me, I'm going to merge it.

**Comment by thelittlebug** [comment]
yes, i can confirm that. thats the reason why it didn't work for me (needed eu-central-1). i tried to change regionName and no connection was possible. so i digged through your source, found that keyname mismatch, tested it local, changed the docs :)

**Pull request merged**
